import { supabase } from '../lib/supabaseClient.js';

/**
 * Creates a unique SHA-256 hash using the Web Crypto API
 * @param {string} message 
 * @returns {Promise<string>}
 */
const generateHash = async (message) => {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
};

/**
 * Generates an immutable audit report for a specific application.
 * @param {string} applicationId - UUID of the loan application
 * @param {string} generatedBy - Name of the user/system creating the report
 * @returns {Promise<{json: any, md: string, hash: string}>}
 */
export const generateAuditReport = async (applicationId, generatedBy = 'SYSTEM') => {
  try {
    // 1. Fetch Session Data (no join — avoids FK schema cache requirement)
    const { data: loanApp, error: appError } = await supabase
      .from('loan_applications')
      .select('*')
      .eq('id', applicationId)
      .single();
    
    if (appError) throw appError;

    // 1b. Fetch profile separately using user_id
    let profileData = null;
    if (loanApp.user_id) {
      const { data: prof } = await supabase
        .from('profiles')
        .select('name, phone')
        .eq('id', loanApp.user_id)
        .single();
      profileData = prof;
    }

    // 2. Fetch KYC Data
    const { data: kycData } = await supabase
      .from('kyc_records')
      .select('*')
      .eq('application_id', applicationId)
      .single();

    // 3. Fetch Events
    const { data: events, error: eventsError } = await supabase
      .from('application_events')
      .select('*')
      .eq('application_id', applicationId)
      .order('created_at', { ascending: true });

    // 4. Fetch Consent Records (uses session_id)
    let consents = [];
    if (loanApp.session_id) {
      const { data: consentData } = await supabase
        .from('consent_records')
        .select('*')
        .eq('session_id', loanApp.session_id)
        .order('captured_at', { ascending: true });
      consents = consentData || [];
    }

    // 4b. Fetch Bureau Report
    const { data: bureauReport } = await supabase
      .from('bureau_reports')
      .select('*')
      .eq('application_id', applicationId)
      .single();

    // 4c. Fetch Regulatory Flags
    const { data: regulatoryFlags } = await supabase
      .from('regulatory_flags')
      .select('*')
      .eq('application_id', applicationId);
      
    // 5. Build JSON Payload mapped precisely for CompliancePage.jsx
    const reportJson = {
      audit_meta: {
        generated_at: new Date().toISOString(),
        generated_by: generatedBy,
        system_version: "2.5.0-compliance",
        environment: {
          userAgent: navigator.userAgent,
          platform: navigator.platform
        }
      },
      applicant: {
        id: loanApp.id,
        name: profileData?.name || loanApp.applicant_name || 'Unknown',
        phone: profileData?.phone || 'Unknown',
        bureau_score: bureauReport?.credit_score || 'N/A',
        stage: loanApp.application_stage,
        status: loanApp.status,
        created_at: loanApp.created_at,
        updated_at: loanApp.updated_at
      },
      risk_assessment: {
        fraud_score: loanApp.fraud_risk_score,
        trust_score: loanApp.trust_score,
        risk_score: loanApp.risk_score,
        flags: regulatoryFlags ? regulatoryFlags.map(f => ({
          severity: f.severity,
          flag_type: f.flag_type,
          description: f.description
        })) : []
      },
      kyc_validation: kycData ? {
        document_type: 'aadhaar', // implicitly default currently
        verified: kycData.biometric_match_status === 'matched',
        face_match_score: kycData.liveness_score ? (kycData.liveness_score * 100).toFixed(0) : 'N/A',
        verification_method: 'LiveKYC.ai Engine',
        document_url: kycData.aadhaar_image_url,
        face_url: kycData.face_capture_url
      } : null,
      consent_audit: consents.map(c => ({
        created_at: c.captured_at,
        user_ip: 'N/A', // user_ip not captured in DB yet
        consent_text: c.consent_phrase
      })),
      event_trail: (events || []).map(e => ({
        created_at: e.created_at,
        event: e.event,
        metadata: e.metadata || {}
      }))
    };

    // 6. Generate SHA-256 Digest
    const serializedReport = JSON.stringify(reportJson);
    const hash = await generateHash(serializedReport);

    // 7. Save Immutable Record to Database
    await supabase.from('audit_reports').insert([{
      application_id: applicationId,
      report_json: reportJson,
      sha256_hash: hash,
      generated_by: generatedBy
    }]);

    // 8. Generate Markdown Format
    const md = `
# Regulatory Audit Report
**Hash:** \`${hash}\`
**Generated At:** ${new Date().toISOString()}
**Generated By:** ${generatedBy}

## 1. Applicant Profile
- **Application ID:** ${loanApp.id}
- **Name:** ${reportJson.applicant.name}
- **Phone:** ${reportJson.applicant.phone}
- **Bureau Score:** ${reportJson.applicant.bureau_score}
- **Status:** ${loanApp.status} (${loanApp.application_stage})

## 2. Risk & KYC Data
- **Fraud Score:** ${loanApp.fraud_risk_score || 'N/A'}
- **KYC Verified:** ${reportJson.kyc_validation?.verified ? 'Yes' : 'No'}

## 3. Explicit Consents
${reportJson.consent_audit.length > 0 ? reportJson.consent_audit.map(c => `- **${new Date(c.created_at).toLocaleString()}**: ${c.consent_text}`).join('\n') : 'No consents recorded.'}

## 4. Event Trail
${reportJson.event_trail.map(e => `- \`[${new Date(e.created_at).toISOString()}]\` - **${e.event}** \n  *Meta:* ${JSON.stringify(e.metadata)}`).join('\n')}

---
*End of Report*
    `.trim();

    return {
      json: reportJson,
      md,
      hash
    };

  } catch (err) {
    console.error('Audit Generation Error', err);
    throw err;
  }
};
